### Local test
GET http://localhost:8080/weather?cep=01014000
x-api-key: API_KEY


### Production test
GET https://go-lab-weather-by-location-7gyhoujojq-uc.a.run.app/weather?cep=01014000
x-api-key: API_KEY